services:
  sepoliar:
    image: sepoliar:1.0.0
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${TZ:-UTC}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
      ENABLED_TOKENS: ${ENABLED_TOKENS}
      WALLET_ADDRESSES: ${WALLET_ADDRESSES}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      SEPOLIAR_ENCRYPTION_KEY: ${SEPOLIAR_ENCRYPTION_KEY}
    volumes:
      - ../data:/app/data:ro
    restart: unless-stopped
